version: '3.8'
services:
  #mysql:
  #  container_name: mysql
  #  image: mysql
  #  ports:
  #    - "3306:3306"
  #  environment:
  #    - MYSQL_ROOT_PASSWORD=sasa
  #  networks:
  #    - stack
  #  healthcheck:
  #    test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-sasa"]
  #    interval: 30s
  #    timeout: 10s
  #    retries: 3

  service1:
    container_name: itca-connect-ldap-crud
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - .env.docker
    networks:
      - stack
    #depends_on:
    #  mysql:
    #    condition: service_healthy
    #  apacheds:
    #    condition: service_healthy
    #environment:
    #  - LDAP_URL=ldap://apacheds:10389
    #  - LDAP_BIND_USER_DN=uid=admin,ou=system
    #  - LDAP_BIND_PASSWORD=secret

  #apacheds:
  #  image: kadimasolutions/apacheds:latest
  #  environment:
  #    - INSTANCE_ID=default
  #    - LDAP_DOMAIN=exampless.com
  #    - LDAP_ADMIN_PASSWORD=secret
  #  tty: true
  #  stdin_open: true
  #  ports:
  #    - 10389:10389
  #    - 10636:10636
  #  volumes:
  #    - apacheds-data:/opt/apacheds/instances/default
  #  networks:
  #    - stack

#volumes:
#  apacheds-data:

################################################################ CREATE STACK NETWORK
#networks:
#  stack:
    #name: stack
    #driver: bridge

networks:
  stack:
    external: true